### ISSUE TITLE
Diversity of revocations

### ISSUE THREAD

**Issue by gerv** [chromium/badssl.com#211]
There are several sorts of revocation - CRL, OCSP, and the Google, MS and Mozilla revoked lists. Is it worth having a subdomain for each? Or perhaps one for CRL/OCSP and another for each of the lists?

Happy to help with getting a cert into the Mozilla list.

Gerv

**Comment by lgarron** [comment]
We already have revoked.badssl.com to test what a revoked cert looks like in a client. It still needs to be added to the Microsoft list (#201), but then we'll be set on that.

What would be a use case for having different combinations of revocation?

**Comment by gerv** [comment]
Different browsers support different mechanisms. Pretty much no new ones support CRLs any more. Some support OCSP, some don't. Obviously, only Google supports CRLsets and Mozilla supports OneCRL. A diversity of revocation types allows you to check what the browser you are testing with supports, particularly if it's not one of the big four.

**Comment by lgarron** [comment]
I can see that being useful.

However, I would like to avoid doing this for `badssl.com` in production, since
1) it is a pretty niche test case, and
2) it would involve maintaining a bunch of extra certs, as well as revocation mechanisms for all of them (which we don't control).

The primary goal of `badssl.com` is to help test security UI, which doesn't significantly depend on the revocation type in any major browser. For that, it suffices to have one revoked certificate, as long as it shows up as revoked in as many cases as possible.

**Comment by gerv** [comment]
Fair enough :-)
