### ISSUE TITLE
Add cookie setting ability and "sent cookie" indicator

### ISSUE THREAD

**Issue by gerv** [chromium/badssl.com#212]
Some browser products allow access to sites with e.g. a mismatched host certificate but throw a UI warning after the site has loaded. The question then arises: has the browser sent the user's authentication information to this potentially-bad site? badssl.com currently makes it hard to tell. It's possible in browsers with dev tools but not all browsers have those. So I suggest the following:

* A button on the front page which says either "Set badssl.com Cookie" or "Clear badssl.com Cookie"
* An indicator on the standard template which says "cookie sent" if the cookie was sent. This could be server-side powered or JS-powered, either is fine.  

Gerv

**Comment by lgarron** [comment]
Could you specify more exactly what you mean? Do you have any particular browsers in mind?

In general, I think we should avoid state as much as possible, especially on the server side.

**Comment by gerv** [comment]
I mean specifically the Qihoo 360 Safe Browser, the most popular in China.

No need for any server-side state. The buttons would use JS to set a cookie, and the template could use JS to read the cookie and display whether it had been sent or not.

**Comment by lgarron** [comment]
> I mean specifically the Qihoo 360 Safe Browser, the most popular in China.

Ah, it's good to have a use case in mind.

> The buttons would use JS to set a cookie, and the template could use JS to read the cookie and display whether it had been sent or not.

I'm still a little fuzzy on what this means. Would it be sufficient to have a page (e.g. at [1common/test1](https://github.com/chromium/badssl.com/tree/master/common/test)`/js-cookie/` that allows setting and reading the cookie for the current domain?

**Comment by gerv** [comment]
There needs to be a page somewhere on the domain which sets a cookie for the domain. That could be anywhere, but I was thinking a button on the front page.

But the indicator which shows whether the cookie has been sent or not needs to be in the standard template used for each problem, so you can tell if cookies got sent to a self-signed site, or to an expired site etc. But that wouldn't need to be visually intrusive - just a small bit of text in the bottom right which said "Cookie sent" if it was sent, and the same as now (i.e. nothing) if it was not. That text could be revealed by a snippet of JS which checked for the presence of the cookie.

**Comment by lgarron** [comment]
I am strongly against adding something to all pages. This is important for visual simplicity as well as overall project simplicity.

> That text could be revealed by a snippet of JS which checked for the presence of the cookie.

Wouldn't a Javascript-accessible cookie be locally accessible regardless of whether it reached the network?

Do you need to guard against cookies being sent with the page load, or with the page being able to send data for a brief while after page load? In the latter case, what's the difference between cookies and e.g. XHR or an image?

**Comment by gerv** [comment]
> I am strongly against adding something to all pages. This is important for visual simplicity as well as overall project simplicity.

I agree; that's why nothing would show up unless someone had set the cookie, which would be a rare event. The amount of code involved is a few lines, no more.

> Wouldn't a Javascript-accessible cookie be locally accessible regardless of whether it reached the network?

A good point. I guess we'd need to check server-side and subst something into the template if it was found (and nothing if it wasn't).

The issue here is that if a browser loads a page with a wrong.host cert regardless, and sends auth cookies, those can be stolen by the MITM. So we want to check whether the browser sends that data automatically. I'm not quite sure how whether or not the page can do XHR is relevant to this issue?

**Comment by lgarron** [comment]
> So we want to check whether the browser sends that data automatically. I'm not quite sure how whether or not the page can do XHR is relevant to this issue?

My point is that the issue isn't really about cookies. It's about whether the exchange with an invalid certificate can leak anything sensitive.

I just tested Qihoo 360 in a Windows 10 VM, and `https://wrong.host.badssl.com/` loads directly:

<img width="1259" alt="screen shot 2016-10-06 at 01 37 34" src="https://cloud.githubusercontent.com/assets/248078/19145828/a5c31256-8b65-11e6-8244-8362a51166da.png">

Since the browser displays the server response, that should be enough to assume that the user's privacy is compromised. Even if no cookies were sent, the response could contain sensitive information. (To pick a random example, it could respond with a random identifier to be used in some following action – think of a ticketing or lottery system.)

If you want further evidence, you can also modify the path to something arbitrary like `https://wrong.host.badssl.com/asdf/`:

<img width="1259" alt="screen shot 2016-10-06 at 01 43 52" src="https://cloud.githubusercontent.com/assets/248078/19146693/75c3d7e4-8b69-11e6-9131-7dfbd178c4cd.png">

This URL is the same origin as the first URL, but with a different path. Since the response depends on the path, this means that you are leaking information about the path. That should be just as scary as cookies for the potential to send sensitive data.
(You can also try to visit e.g. a path of `/robots.txt` to see that the response seems to be based on the full path.)

Is that a sufficiently useful approach for testing your concerns?

**Comment by gerv** [comment]
Well yes, it's possible that even in the absence of authentication information the server could return sensitive information, but its a lot less likely. But anyway, I managed to find another way of testing this - I found a site where I had an existing cookie-based login, and told Windows to temporarily not trust the root that the site used. Then it was possible to prove that cookies were sent.

Thanks!
