### ISSUE TITLE
ER: Certificate without SAN

### ISSUE THREAD

**Issue by Valf203** [chromium/badssl.com#338]
In light of Chrome 66 dropping the legacy flag for enabling name matching against CN, can badssl.com host something using a certificate with only a CN but no SAN?

**Comment by lgarron** [comment]
No, this is against the Baseline Requirements, so CAs are not allowed to
issue such a cert. We do have a no-san subdomain for when you run badssl.com
for local development, though:

https://github.com/chromium/badssl.com/blob/master/domains-local-only/cert/no-san.conf

**Comment by lgarron** [comment]
I'm closing this since we already have `no-san` support as much as we can (except possibly one issued by a distrusted CA). Let us know if you need help with trying it locally!

**Comment by JeremyRand** [comment]
Would it be feasible to use the `untrusted-root` CA to issue a certificate for `no-san` on the public BadSSL site?  This would work for my purposes; importing a root CA for test purposes is a lot easier than setting up the local development version of the site.

**Comment by lgarron** [comment]
> Would it be feasible to use the untrusted-root CA to issue a certificate for no-san on the public BadSSL site?

This would go against the purpose of badssl.com, which is to serve responses that exhibit specific responses with respect to public PKI. Using a private root is sufficient to make the request fail, which can easily lead to false positives in testing.

**Comment by jkldgoefgkljefogeg** [comment]
This can actually be useful for things like browser compatibility testing. Chrome for desktop allows bypass missing SAN, yet Chrome android throws a ERR_SSL_PROTOCOL_ERROR. I ran into this problem with some IoT device's factory shipped certificate, which was quite a surprise / confusing

since badssl has its own CA for self signed / untrusted root, adding another test for no SAN would be awesome.
