### ISSUE TITLE
Is there a schedule that the websites will support tls1.3

### ISSUE THREAD

**Issue by wolftian** [chromium/badssl.com#384]
1， Will it support 0-RTT
2， Or certificate checking while TLS1.3

**Comment by christhompson** [comment]
Merging this into #332 which has more discussion on how we might implement this. It's on my radar but it's reasonably complicated to set up without breaking existing tests (of the "badssl" variety). Priority goes to keeping the edge cases around more than the common cases (since they are by nature harder to find test cases for).
