### ISSUE TITLE
Certificate https://revoked.badssl.com/ has expired

### ISSUE THREAD

**Issue by mjeffrey** [chromium/badssl.com#515]
The certificate above has now expired. Could it be replaced? Thanks!

**Comment by natluqwerty** [comment]
please!!! 🙏

**Comment by drauch** [comment]
Also the CRL for this certificate is empty? So it is not really revoked anymore?!

**Comment by szhu25** [comment]
> Also the CRL for this certificate is empty? So it is not really revoked anymore?!

Because the issuer certificate (intermediate certificate by RapidSSL/Digicert) also expired on May 31st, 2023...

**Comment by popeanga94** [comment]
Any updates on this issue? It would be very helpful if the certificate for https://revoked.badssl.com/ would be replaced with one that is not expired. Thx!

**Comment by levon-vardevanyan-solarwinds** [comment]
Happy New Year! It's 2024 already - no plans to bring it back to life? This resource was actually tremendously helpful, looks like back in 2021 some amazing folks managed to fix it https://github.com/chromium/badssl.com/issues/477 maybe @BenWilson-Mozilla and @christhompson still have some knowledge/connection to resurrect it?


Meanwhile if anyone's wondering you can try using https://www.digicert.com/kb/digicert-root-certificates.htm

**Comment by gamer191** [comment]
I understand that this issue might not be worth fixing. However, please at least remove that domain, because currently it's misleading, since it suggests that every tested program that blocks expired certificates is capable of checking certificate revokation status

**Comment by christhompson** [comment]
Apologies for the long-expired cert here. The revoked test case was particularly painful to renew because we previously were manually issuing and revoking it, and then manually adding it to Chrome's certificate blocklist. I've switched this test case over to be included in our automated certificate renewal system using Lets Encrypt + ACME -- this means that it will just be marked as revoked in the CRLs, which may have different behavior across browsers, but it does mean it will automatically be kept renewed along with the other main certs for the site.
